@Library('library')_

pipeline
{
    agent any
    stages
    {
        stage('ContinuousDownload_Master')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/krishnain/newjava.git")
                }
            }
        }
        stage('ContinuousBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.newMaven()
                }
            }
        }
        stage('ContinuousDeployment_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("http://172.31.7.63:8080","testapp")
                }
            }
        }
        stage('ContinuousTesting_Master')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/intelliqittrainings/FunctionalTesting.git")
                    cicd.newSelenium("/home/ubuntu/.jenkins/workspace/Pipelinewithlibraries/")
                }
            }
        }
        stage('ContinuousDeploy_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("http://172.31.15.5:8080","prodapp")
                    
                }
            }
        }
       
    }
}
